# https://docs.microsoft.com/azure/devops/pipelines/languages/android
parameters:
  name: 'android_integration_tests'
  vmImage: 'macOS-10.15'
  sdkVersion: 28
  platformVersion: 9.0
  emuTag: default
  emuArch: x86
  testName: ''

jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    variables:
      TERM: dumb
      ANDROID_AVD: testemulator
      ANDROID_SDK_VERSION: ${{ parameters.sdkVersion }}
      PLATFORM_VERSION: ${{ parameters.platformVersion }}
      EMU_TAG: ${{ parameters.emuTag }}
      EMU_ARCH: ${{ parameters.emuArch }}
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: $(NODE_VERSION)
    - script: npm install
      displayName: Install Node Dependencies
    - script: bash .azure-templates/scripts/start-emulator.sh
      displayName: Create And Run Emulator
    - script: |-
        nohup adb logcat -v time *:S appium:V appium-e2e-tests:V TestRunner:V *:E *:F > logcat.txt &
        ./gradlew connectedE2eTestDebugAndroidTest \
          -Pandroid.testInstrumentationRunnerArguments.class=io.appium.uiautomator2.unittest.test.${{ parameters.testName }} \
          -Pandroid.testInstrumentationRunnerArguments.notAnnotation=io.appium.uiautomator2.unittest.test.internal.SkipHeadlessDevices
      env:
        JAVA_HOME: $(JAVA_HOME_11_X64)
        PATH: $(JAVA_HOME_11_X64)/bin:$(PATH)
      displayName: Run Tests
    - script: cat logcat.txt
      condition: always()
      displayName: Show Logs
